# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes

DISABLE_LINTERS:
  - TYPESCRIPT_STANDARD
  - JAVASCRIPT_STANDARD

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true

JAVASCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_DEFAULT_STYLE: prettier
LINTER_RULES_PATH: .
PRINT_ALPACA: false

PRE_COMMANDS:
  - command: "npm ci --force --include=dev"
    cwd: "workspace"
POST_COMMANDS:
  - command: "npm run format"
    cwd: "workspace"
  - command: "npm run lint"
    cwd: "workspace"
IGNORE_GITIGNORED_FILES: true

# TYPESCRIPT_ES_CLI_LINT_MODE: project
# JSON_PRETTIER_CLI_LINT_MODE: project
# YAML_PRETTIER_CLI_LINT_MODE: project
# TYPESCRIPT_PRETTIER_CLI_LINT_MODE: project
CLEAR_REPORT_FOLDER: true
SPELL_CSPELL_ANALYZE_FILE_NAMES: false
